compute:

  provider:
    credentials: ${GRID_PROVIDER_CREDENTIALS}
    region: us-east-1
    vendor: aws

  train:
    disk_size: 200
    instance: t2.2xlarge
    cpus: 7
    gpus: 0
    memory: 32G
    framework: lightning

    datastore_name: ${GRID_DATASTORE_NAME}
    datastore_version: ${GRID_DATASTORE_VERSION}
    datastore_mount_dir: ${GRID_DATASTORE_MOUNT_DIR}

    environment:
      GRID_USERNAME: ${GRID_USERNAME}
      GRID_API_KEY: ${GRID_API_KEY}

    actions:
      on_image_build:
        - apt-get install wget -y
        - pip install lightning-grid
